---
title: "proj1"
author: "Khoi Tran (kt2np)"
date: "November 16, 2020"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(stringi)
library(stringr)
library(readr)
library(rvest)
library(twitteR)

## burner twitter profile
## used just for scraping data for this project
## choose 'no' when asked to use a local file for token
setup_twitter_oauth('2PRpIuOuFUMjw6glM5WoYlEpw', 
                    'inbMp0C9wfAKHYd3Wl5WstDSRDzEwEeqSmWATw9ZiB23uAU5Px', 
                    '1332888461905448962-Ew4sIQBnhBfSMpZyR4nJgJ5MBXaDAP', 
                    'nKNXV2Qp8LqZ39ZuLlIEqFdsnX9lfmeVzEiolGZcBuUB4')

## reading in data
playerstats <- read.csv(file = 'nba_player_stats.csv', header = TRUE)
playersalary <- read.csv(file = 'nba_salary.csv', header = TRUE, skip = 1)
```

```{r}
## cleaning data
# player name, team, salaries for 2019-2020 season only
# drop first column from player salaries
playersalary <- playersalary[-c(1), c(2, 3, 4, 10, 11)]

# drop first column from player stats
playerstats <- playerstats[-c(1)]

# change data types for 'playersalary'
playersalary <- transform(playersalary, 
                          Player = as.character(Player), 
                          Tm = as.character(Tm), 
                          X2019.20 = as.character(X2019.20) %>% parse_number(), 
                          Signed.Using = as.character(Signed.Using), 
                          Guaranteed = as.character(Guaranteed) %>% parse_number())

# aggregate player stats for season-long total, to account for mid-season trades
# aggregate player positions as well, separately
# use 'head' function to grab instances of players playing multiple positions
playerstats_agg <- merge(aggregate(playerstats[2:3], by = playerstats['Player'], FUN = head, 1), 
                         aggregate(playerstats[5:29], by = playerstats['Player'], FUN = sum), 
                         by = c('Player'))

# aggregate player salary for season-long total, to account for mid-season trades# aggregate on max values for salary and guarantees, per player and per team
playersalary_agg <- aggregate(playersalary[c(3, 5)], by = list(playersalary$Player, playersalary$Tm), FUN = max)

# aggregate this data frame again, this time by player alone, to find total salary per player of the 2019-2020 season
playersalary_agg <- aggregate(playersalary_agg[3:4], by = playersalary_agg[1], FUN = sum)
names(playersalary_agg)[1] <- 'Player'

# merge aggregated 'playerstats' with 'playersalary' on player names
player_salarystats <- merge(playersalary_agg, 
                            playerstats_agg, 
                            by = c('Player'))

## get url for per-player stats
player_salarystats$url <- strsplit(player_salarystats$Player, '\\', fixed = TRUE)
# cleaned player names
player_salarystats$Player <- sapply(player_salarystats$url, `[[`, 1)
# part of player profile url
player_salarystats$url <- sapply(player_salarystats$url, `[[`, 2)
# full player profile url, from basketball-reference.com
player_salarystats$url <- stri_join('https://www.basketball-reference.com/players/', 
                                    substr(player_salarystats$url, start = 1, stop = 1), '/',
                                    player_salarystats$url, '.html')
```

```{r}
# create function for shortening xpaths
xpath_short <- function(contains, xpath) {
  if(missing(xpath)) {
    # if there is no appending xpath
    xpath_final <- paste('//div[@id="wrap"]//div[@id="meta"]/div[@itemscope]/p[contains(., "', 
                           contains, 
                           '")]', 
                           sep = '')
  } else {
    # if there is an appending xpath
    xpath_final <- paste('//div[@id="wrap"]//div[@id="meta"]/div[@itemscope]/p[contains(., "', 
                           contains, 
                           '")]', 
                           xpath, 
                           sep = '')
  }
  return(xpath_final)
}
```

```{r}
## lists to add variables to data frame with
new_vars <- c('yrs_exp', 'age_yrs', 
              'draft_num', 'debut_yr', 
              'num_accolades', 'num_teams_1920', 
              'mid_season_trades', 'team', 
              'num_yrs_current_team', 'num_teams_played', 
              'injury_yrs', 'twitter_followers')
player_salarystats[, new_vars] <- NA
```

```{r}
## for loop, scraping data per-player, per-game stats
for (i in 1:nrow(player_salarystats)) {
  ### scrape table of total player stats
  # split on the empty row, create if-then for this, as not all players will have a per-team section of the table
  # need to aggregate data, multiply per-game stats by num games played per-season, per-team to recalculate total values
  player_stats <- read_html(player_salarystats$url[i]) %>% 
                    html_nodes('table') %>% 
                    html_table() %>% 
                    data.frame()
  
  ## if statement to separate table, as it includes summary stats for more veteran players (have been traded)
  ## modify to to account for injury (separate if statement?)
  # e.g. for 30th player, Ben Simmons ('https://www.basketball-reference.com/players/s/simmobe01.html')
  if (grepl('injury', player_stats$Tm, fixed = TRUE)) {
    # set num years injured to number of rows where injury was indicated
    player_salarystats$injury_yrs[i] <- grepl('injury', player_stats$Tm, fixed = TRUE) %>% 
                                          sum()
    # subset table to exclude injury year rows, as it is not cleanly formatted data
    player_stats <- player_stats[!grepl('injury', player_stats$Tm, fixed = TRUE), ]
  } else {
    # set num injured years to zero if there is no row indicating the player missed a season due to injury
    player_salarystats$injury_yrs[i] = 0
  }
  
  # set player stats data where applicable to numeric values
  player_stats[, 6:30] <- sapply(player_stats[, 6:30], as.numeric)
  
  if ('' %in% player_stats$Season) {
    # if there is a blank row in the scraped table, then the player has been traded
    # there will be a second partition to the table
    player_stats_per_season <- player_stats[1:(which(player_stats$Season == '') - 1),]
    
    # part of the scraped table that does not exist if there is no blank row
    # player stats by team they have played ondf
    player_stats_per_team <- player_stats[(which(player_stats$Season == '') + 1):nrow(player_stats),]
    
    # cleaning per team df
    # table scraped is per-game, so multiply certain variables by number of games played
    player_stats_per_team[-c(1:8, 11, 14, 17, 18, 21)] <- sapply(player_stats_per_team[-c(1:8, 11, 14, 17, 18, 21)] * 
                                                                 player_stats_per_team$G, round)
    
    ## num teams Played For, total
    ## see: if statement above, set to 1 if never traded
    player_salarystats$num_teams_played[i] <- nrow(player_stats_per_team)
    
  } else {
    # if there is no blank row in the scraped table, then the player has never been traded
    player_stats_per_season <- player_stats
    
    ## num teams Played For, total
    ## see: if statement above, set to 1 if never traded
    player_salarystats$num_teams_played[i] <- 1
  }
  
  # table scraped is per-game, so multiply certain variables by number of games played
  # multiply everything but 1:6, 11, 14, 17, 18, 21 (all per-game stats) by player_stats_per_season$MP
  # round everything for totals
  player_stats_per_season[-c(1:8, 11, 14, 17, 18, 21)] <- sapply(player_stats_per_season[-c(1:8, 11, 14, 17, 18, 21)] * 
                                                                   player_stats_per_season$G, round)
  
  ### assign variables to data frame
  ### separate player_stats_per_team for just 2019-20 season to create several variables
  player_stats_1920 <- player_stats_per_season[which(player_stats_per_season$Season == '2019-20'), ]
  ## num teams Played For in 2019-20 season
  player_salarystats$num_teams_1920[i] <- player_stats_1920 %>% 
                                            nrow()
  ## number of mid-season trades (num teams in 2019-20 - 1)
  # untraded players will have 0
  player_salarystats$mid_season_trades[i] <- player_stats_1920 %>% 
                                              nrow() - 1
  ## final team (for 'Team' stat in aggr df)
  player_salarystats$team[i] <- tail(player_stats_1920$Tm, n = 1)
  # num yrs played with current team
  # will be '1' if mid-season traded
  player_salarystats$num_yrs_current_team[i] <- sum(player_stats_per_season$Tm == player_salarystats$team[i])
  
  ## read_html() per player url
  player_url <- read_html(player_salarystats$url[i])
  ## NBA experience
  player_salarystats$yrs_exp[i] <- player_url %>% 
                                    html_node(xpath = xpath_short('Experience')) %>% 
                                    html_text() %>% 
                                    str_extract('\\d+') %>% 
                                    as.numeric()
  ## Age
  # 365.2422 days per year, use datetime functions
  player_salarystats$age_yrs[i] <- difftime(Sys.Date(), 
                                            player_url %>% 
                                              html_node(xpath = xpath_short('Born', '/span/@data-birth')) %>% 
                                              html_text(), 
                                            units = 'days') %>% 
                                    as.numeric() / 365.2422
  ## Draft Pick
  # 'stri_extract_last_regex' picks last number in string
  # 30 picks per draft round, calculate draft round off this after creating df
  player_salarystats$draft_num[i] <- player_url %>% 
                                      html_node(xpath = xpath_short('Draft', '/a[1]/following-sibling::text()')) %>% 
                                      html_text() %>% 
                                      stri_extract_last_regex('\\d+') %>% 
                                      as.numeric()
  ## Draft Year
  # 'stri_extract_last_regex' picks last number in string
  ## replace with 'Debut Year' variable
  player_salarystats$debut_yr[i] <- player_url %>% 
                                      html_node(xpath = xpath_short('Debut', '/a')) %>% 
                                      html_text() %>% 
                                      stri_extract_last_regex('\\d+') %>% 
                                      as.numeric()
  ## Num Accolades
  player_salarystats$num_accolades[i] <- player_url %>% 
                                          html_node(xpath = '//div[@id="wrap"]//ul[@id="bling"]') %>% 
                                          as.character() %>% 
                                          str_count(pattern = '</a>')
  
  ## Twitter profile
  twitter_profile <- tryCatch(player_url %>% 
                                html_node(xpath = xpath_short('Twitter', '/a[contains(@href, "twitter.com")]/text()')) %>% 
                                html_text() %>% 
                                getUser(), 
                              error = function(err) NA)
  
  
  ## if statement to handle invalid or nonexistent Twitter profiles
  ## WARNING: slow and will have lots of red text in your console
  if (is.na(twitter_profile)) {
    # if a valid twitter profile cannot be found, set followers = 0
    player_salarystats$twitter_followers[i] <- 0
  } else {
    # if a valid twitter profile can be found, return num followers
    player_salarystats$twitter_followers[i] <- twitter_profile$followersCount
  }
}

## replace NAs with 0
# e.g. draft_num (not all players were drafted) and num_accolades (not all players have accolades)
player_salarystats[is.na(player_salarystats)] <- 0

## set team, position as factor variables

## code to spit out new csv for combined dataset
write.csv(player_salarystats, 'NBA_salary_stats.csv')
```

