---
title: "Data Analysis"
author: "Jordan Hiatt"
date: "12/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(corrplot)
library(GGally)
library(PerformanceAnalytics)
library(plotly)
```


```{r}
# Jordan

# save the data seperately
jh_data <- read.csv(file = 'NBA_salary_stats.csv', row.names = 1, header = TRUE)

# Correlation plot (Khoi's code)
corrplot(cor(jh_data[, -c(1, 4, 31, 39)], 
        use = 'complete.obs'), 
        method = 'circle', 
        type = 'upper')

# Just correlation of all vars with y
correlations<-cor(jh_data[, -c(1,3,4, 5, 31, 39)])[ ,1]

# save the highly correlated variables (above .5 is my threshold)
high_cor <- Filter(function(x) x>.5,correlations)

# remove the y variable
high_cor<-high_cor[2:length(high_cor)]

# Loop through all highly correlated vars to get regressions and plots
for (c in names(high_cor)) {
  # get the model for each highly correlated predictor
  l<-lm(jh_data$X2019.20~jh_data[[c]])
  
  # plot the model with the regression line
  plot(jh_data$X2019.20~jh_data[[c]], main=c)
  abline(l,col='red')
}
```


```{r}
# Jordan
# automated search procedures

# !! Do we want to split the data and do crosswise regression?
##intercept only model
regnull <- lm(jh_data$X2019.20~1, data=jh_data)

##model with all predictors
regfull <- lm(X2019.20~.-Player-Guaranteed-Age-url-team, data=jh_data)

step_reg <- step(regnull, scope=list(lower=regnull, upper=regfull), direction="both")
```

```{r}
jh_data$Pos<-factor(jh_data$Pos)
is.factor(jh_data$Pos)

levels(jh_data$Pos)
contrasts(jh_data$Pos)

a1<-subset(jh_data,Pos=="C")
a2<-subset(jh_data,Pos=="C-PF")
a3<-subset(jh_data,Pos=="PF")
a4<-subset(jh_data,Pos=="PF-C")
a5<-subset(jh_data,Pos=="PF-SF")
a6<-subset(jh_data,Pos=="PG")
a7<-subset(jh_data,Pos=="PG-SG")
a8<-subset(jh_data,Pos=="SF")
a9<-subset(jh_data,Pos=="SF-C")
a10<-subset(jh_data,Pos=="SF-PF")
a11<-subset(jh_data,Pos=="SF-SG")
a12<-subset(jh_data,Pos=="SG")
a13<-subset(jh_data,Pos=="SG-PG")
a14<-subset(jh_data,Pos=="SG-SF")


reg1<-lm(Guaranteed~PTS,data=a1)
reg2<-lm(Guaranteed~PTS,data=a2)
reg3<-lm(Guaranteed~PTS,data=a3)
reg4<-lm(Guaranteed~PTS,data=a4)
reg5<-lm(Guaranteed~PTS,data=a5)
reg6<-lm(Guaranteed~PTS,data=a6)
reg7<-lm(Guaranteed~PTS,data=a7)
reg8<-lm(Guaranteed~PTS,data=a8)
reg9<-lm(Guaranteed~PTS,data=a9)
reg10<-lm(Guaranteed~PTS,data=a10)
reg11<-lm(Guaranteed~PTS,data=a11)
reg12<-lm(Guaranteed~PTS,data=a12)
reg13<-lm(Guaranteed~PTS,data=a13)
reg14<-lm(Guaranteed~PTS,data=a14)

plot(jh_data$PTS,jh_data$Guaranteed, main="Guaranteed against PTS, by Manufacturer")
points(a2$PTS,a2$Guaranteed, pch=2, col="red")
points(a3$PTS,a3$Guaranteed, pch=3, col="blue")
points(a4$PTS,a4$Guaranteed, pch=4, col="green")
points(a5$PTS,a5$Guaranteed, pch=5, col="orange")
points(a6$PTS,a6$Guaranteed, pch=6, col="purple")
points(a7$PTS,a7$Guaranteed, pch=7, col="pink")
points(a8$PTS,a8$Guaranteed, pch=8, col="seagreen2")
points(a9$PTS,a9$Guaranteed, pch=9, col="salmon3")
points(a10$PTS,a10$Guaranteed, pch=10, col="royalblue4")
points(a11$PTS,a11$Guaranteed, pch=11, col="rosybrown4")
points(a12$PTS,a12$Guaranteed, pch=12, col="skyblue2")
points(a13$PTS,a13$Guaranteed, pch=13, col="slateblue2")
points(a14$PTS,a14$Guaranteed, pch=14, col="slategray2")

abline(reg1,lty=1)
abline(reg2,lty=2, col="red")
abline(reg3,lty=3, col="blue")
abline(reg4,lty=4, col="green")
abline(reg5,lty=5, col="orange")
abline(reg6,lty=6, col="purple")
abline(reg7,lty=7, col="pink")
abline(reg8,lty=8, col="seagreen2")
abline(reg9,lty=9, col="salmon3")
abline(reg10,lty=10, col="royalblue4")
abline(reg11,lty=11, col="rosybrown4")
abline(reg12,lty=12, col="skyblue2")
abline(reg13,lty=13, col="slateblue2")
abline(reg14,lty=14, col="slategray2")
```

